const uiTypes: { [key: string]: string } = {
  SET_CHARACTER_PAGE_CHARACTER_DATA_FETCHING: 'SET_CHARACTER_PAGE_CHARACTER_DATA_FETCHING',
  SET_CHARACTER_PAGE_CHARACTER_DATA_FETCHED: 'SET_CHARACTER_PAGE_CHARACTER_DATA_FETCHED',
  SET_CHARACTER_PAGE_CHARACTER_DATA_FETCH_FAILED: 'SET_CHARACTER_PAGE_CHARACTER_DATA_FETCH_FAILED',
  SET_CHARACTER_PAGE_CHARACTER_DATA_FETCH_FAILED_MESSAGE:
    'SET_CHARACTER_PAGE_CHARACTER_DATA_FETCH_FAILED_MESSAGE',
  SET_CHARACTER_PAGE_CHARACTER_RANKINGS_FETCHING: 'SET_CHARACTER_PAGE_CHARACTER_RANKINGS_FETCHING',
  SET_CHARACTER_PAGE_CHARACTER_RANKINGS_FETCHED: 'SET_CHARACTER_PAGE_CHARACTER_RANKINGS_FETCHED',
  SET_CHARACTER_PAGE_CHARACTER_RANKINGS_FETCH_FAILED:
    'SET_CHARACTER_PAGE_CHARACTER_RANKINGS_FETCH_FAILED',
  SET_CHARACTER_PAGE_CHARACTER_RANKINGS_FETCH_FAILED_MESSAGE:
    'SET_CHARACTER_PAGE_CHARACTER_RANKINGS_FETCH_FAILED_MESSAGE',
};

export default uiTypes;
